-- fix al spawm CreatureTextMgr: Could not find Text for Creature(Taurajo Refugee) Entry 37487 in 'creature_text' table. Ignoring.
DELETE FROM `creature_template` WHERE `entry`=37487;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `currencyId`, `currencyCount`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (37487, 0, 0, 0, 0, 0, 30612, 30613, 30614, 0, 'Taurajo Refugee', '', '', 0, 26, 28, 0, 0, 104, 104, 0, 1, 1.14286, 1, 1.14286, 1, 0, 39, 53, 0, 96, 1, 2000, 2000, 1, 512, 2048, 2048, 0, 0, 0, 0, 0, 27, 40, 8, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 'SmartAI', 0, 3, 0, 1.5, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, '', 13623);

DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 0, 'I remember when the Barrens was ... barren. And we liked it!', 12, 0, 100, 5, 0, 0, 37147, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=1;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 1, 'I\'ve had enough of this jungle!', 12, 0, 100, 5, 0, 0, 37143, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=2;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 2, 'Get ... me ... out of here!', 12, 0, 100, 5, 0, 0, 37144, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=3;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 3, 'I think this jungle wants to eat me!', 12, 0, 100, 1, 0, 0, 37145, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=4;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 4, 'Thank you! That thing was shaking me like a ragdoll.', 12, 0, 100, 5, 0, 0, 37146, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=0 AND `id`=5;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 0, 5, 'Whew! I\'m never eating asparagus again.', 12, 0, 100, 5, 0, 0, 37142, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=1 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 1, 0, 'I only understand a few words of the quilboar tongue, but I didn\'t like what I heard.', 12, 0, 100, 1, 0, 0, 37122, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=1 AND `id`=1;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 1, 1, 'You\'re a savior! I don\'t know what those things wanted from us...', 12, 0, 100, 1, 0, 0, 37124, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=1 AND `id`=2;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 1, 2, 'Free at last!', 12, 0, 100, 5, 0, 0, 18707, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=1 AND `id`=3;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 1, 3, 'Are the refugees still gathering at Camp Una\'fe?', 12, 0, 100, 6, 0, 0, 37123, '');
DELETE FROM `creature_text` WHERE `entry`=37487 AND `groupid`=1 AND `id`=4;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES (37487, 1, 4, 'Thank you!', 12, 0, 100, 5, 0, 0, 18708, '');
