DROP TABLE IF EXISTS `arena_log`;

CREATE TABLE `arena_log` (
  `endTime` int(11) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `winnerTeam` mediumint(9) DEFAULT NULL,
  `looserTeam` mediumint(9) DEFAULT NULL,
  `winnerRating` mediumint(9) DEFAULT NULL,
  `winnerMMR` mediumint(9) DEFAULT NULL,
  `looserRating` mediumint(9) DEFAULT NULL,
  `looserMMR` mediumint(9) DEFAULT NULL,
  `winpl1` text COLLATE utf8mb4_unicode_ci,
  `winpl2` text COLLATE utf8mb4_unicode_ci,
  `winpl3` text COLLATE utf8mb4_unicode_ci,
  `winpl4` text COLLATE utf8mb4_unicode_ci,
  `winpl5` text COLLATE utf8mb4_unicode_ci,
  `loosepl1` text COLLATE utf8mb4_unicode_ci,
  `loosepl2` text COLLATE utf8mb4_unicode_ci,
  `loosepl3` text COLLATE utf8mb4_unicode_ci,
  `loosepl4` text COLLATE utf8mb4_unicode_ci,
  `loosepl5` text COLLATE utf8mb4_unicode_ci,
  `windmg` int(11) DEFAULT NULL,
  `winheal` int(11) DEFAULT NULL,
  `winkill` tinyint(4) DEFAULT NULL,
  `loosedmg` int(11) DEFAULT NULL,
  `looseheal` int(11) DEFAULT NULL,
  `loosekill` tinyint(4) DEFAULT NULL,
  `winIP1` mediumtext COLLATE utf8mb4_unicode_ci,
  `winIP2` mediumtext COLLATE utf8mb4_unicode_ci,
  `winIP3` mediumtext COLLATE utf8mb4_unicode_ci,
  `winIP4` mediumtext COLLATE utf8mb4_unicode_ci,
  `winIP5` mediumtext COLLATE utf8mb4_unicode_ci,
  `looseIP1` mediumtext COLLATE utf8mb4_unicode_ci,
  `looseIP2` mediumtext COLLATE utf8mb4_unicode_ci,
  `looseIP3` mediumtext COLLATE utf8mb4_unicode_ci,
  `looseIP4` mediumtext COLLATE utf8mb4_unicode_ci,
  `looseIP5` mediumtext COLLATE utf8mb4_unicode_ci,
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;
